-- Stap 8 — reserveringen centraal bewerken en welkomstcalls uitbreiden
-- Voer dit één keer uit in Supabase > SQL Editor.

alter table if exists public.res_koppeling
  add column if not exists resource_id text,
  add column if not exists totaal numeric(10,2),
  add column if not exists betaald numeric(10,2),
  add column if not exists arrangement text,
  add column if not exists extra text,
  add column if not exists notitie text,
  add column if not exists welkomstcall_datum date,
  add column if not exists welkomstcall_tijd time,
  add column if not exists welkomstcall_medewerker text,
  add column if not exists welkomstcall_status text,
  add column if not exists welkomstcall_notitie text;

create table if not exists public.wz_welkomstcalls (
  id bigint generated by default as identity primary key,
  gast text,
  telefoon text,
  email text,
  locatie text,
  aankomst date,
  reservering text,
  gepland_datum date,
  gepland_tijd time,
  medewerker text,
  status text not null default 'open',
  notitie text,
  aangemaakt timestamptz not null default now(),
  bijgewerkt timestamptz not null default now()
);

alter table public.wz_welkomstcalls
  add column if not exists gepland_datum date,
  add column if not exists gepland_tijd time,
  add column if not exists medewerker text,
  add column if not exists status text default 'open',
  add column if not exists notitie text,
  add column if not exists bijgewerkt timestamptz default now();

create index if not exists wz_welkomstcalls_reservering_idx
  on public.wz_welkomstcalls (reservering);

create index if not exists wz_welkomstcalls_planning_idx
  on public.wz_welkomstcalls (gepland_datum, gepland_tijd)
  where status is distinct from 'afgerond';

select 'stap 8 gereed' as resultaat;
